-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_module_preProcessing is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    msg_strm5_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    msg_strm5_num_data_valid : IN STD_LOGIC_VECTOR (15 downto 0);
    msg_strm5_fifo_cap : IN STD_LOGIC_VECTOR (15 downto 0);
    msg_strm5_empty_n : IN STD_LOGIC;
    msg_strm5_read : OUT STD_LOGIC;
    len_strm6_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    len_strm6_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    len_strm6_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    len_strm6_empty_n : IN STD_LOGIC;
    len_strm6_read : OUT STD_LOGIC;
    end_len_strm7_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    end_len_strm7_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    end_len_strm7_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    end_len_strm7_empty_n : IN STD_LOGIC;
    end_len_strm7_read : OUT STD_LOGIC;
    blk_strm_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    blk_strm_num_data_valid : IN STD_LOGIC_VECTOR (13 downto 0);
    blk_strm_fifo_cap : IN STD_LOGIC_VECTOR (13 downto 0);
    blk_strm_full_n : IN STD_LOGIC;
    blk_strm_write : OUT STD_LOGIC;
    nblk_strm8_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    nblk_strm8_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    nblk_strm8_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    nblk_strm8_full_n : IN STD_LOGIC;
    nblk_strm8_write : OUT STD_LOGIC;
    end_nblk_strm11_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    end_nblk_strm11_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    end_nblk_strm11_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    end_nblk_strm11_full_n : IN STD_LOGIC;
    end_nblk_strm11_write : OUT STD_LOGIC );
end;


architecture behav of top_module_preProcessing is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv59_2 : STD_LOGIC_VECTOR (58 downto 0) := "00000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv59_1 : STD_LOGIC_VECTOR (58 downto 0) := "00000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv448_lc_1 : STD_LOGIC_VECTOR (447 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv512_lc_2 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal len_strm6_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal end_len_strm7_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal blk_strm_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln343_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal cmp116_reg_668 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln343_reg_664 : STD_LOGIC_VECTOR (0 downto 0);
    signal nblk_strm8_blk_n : STD_LOGIC;
    signal end_nblk_strm11_blk_n : STD_LOGIC;
    signal len_reg_634 : STD_LOGIC_VECTOR (63 downto 0);
    signal left_fu_264_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal left_reg_641 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln485_fu_268_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln485_reg_647 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln_fu_272_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal trunc_ln_reg_654 : STD_LOGIC_VECTOR (57 downto 0);
    signal trunc_ln299_fu_286_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln299_reg_659 : STD_LOGIC_VECTOR (1 downto 0);
    signal cmp116_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_reg_673 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal trunc_ln1_reg_678 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln375_fu_391_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln375_reg_683 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_255_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_688 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_idle : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_ready : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_msg_strm5_read : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_write : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_idle : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_ready : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_msg_strm5_read : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_15_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_15_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_14_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_14_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_13_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_13_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_12_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_12_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_11_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_11_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_10_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_10_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_9_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_8_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_8_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_7_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_7_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_6_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_6_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_5_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_5_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_4_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_3_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_2_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_1_out_ap_vld : STD_LOGIC;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_out_ap_vld : STD_LOGIC;
    signal end_flag_3_reg_211 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_predicate_op102_write_state9 : BOOLEAN;
    signal ap_block_state9 : BOOLEAN;
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_block_state2 : BOOLEAN;
    signal or_ln365_1_fu_360_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal or_ln471_s_fu_447_p17 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_state8 : BOOLEAN;
    signal or_ln467_s_fu_484_p18 : STD_LOGIC_VECTOR (511 downto 0);
    signal or_ln489_s_fu_522_p5 : STD_LOGIC_VECTOR (511 downto 0);
    signal icmp_ln299_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln299_fu_296_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln299_fu_282_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal blk_num_fu_304_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal or_ln_fu_325_p5 : STD_LOGIC_VECTOR (511 downto 0);
    signal or_ln365_fu_336_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_24_fu_342_p4 : STD_LOGIC_VECTOR (479 downto 0);
    signal or_ln365_s_fu_352_p3 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_fu_367_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_condition_355 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component top_module_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        msg_strm5_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        msg_strm5_num_data_valid : IN STD_LOGIC_VECTOR (15 downto 0);
        msg_strm5_fifo_cap : IN STD_LOGIC_VECTOR (15 downto 0);
        msg_strm5_empty_n : IN STD_LOGIC;
        msg_strm5_read : OUT STD_LOGIC;
        trunc_ln : IN STD_LOGIC_VECTOR (57 downto 0);
        blk_strm_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        blk_strm_num_data_valid : IN STD_LOGIC_VECTOR (13 downto 0);
        blk_strm_fifo_cap : IN STD_LOGIC_VECTOR (13 downto 0);
        blk_strm_full_n : IN STD_LOGIC;
        blk_strm_write : OUT STD_LOGIC );
    end component;


    component top_module_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        msg_strm5_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        msg_strm5_num_data_valid : IN STD_LOGIC_VECTOR (15 downto 0);
        msg_strm5_fifo_cap : IN STD_LOGIC_VECTOR (15 downto 0);
        msg_strm5_empty_n : IN STD_LOGIC;
        msg_strm5_read : OUT STD_LOGIC;
        select_ln375 : IN STD_LOGIC_VECTOR (3 downto 0);
        zext_ln375 : IN STD_LOGIC_VECTOR (2 downto 0);
        trunc_ln299_1 : IN STD_LOGIC_VECTOR (1 downto 0);
        cmp203 : IN STD_LOGIC_VECTOR (0 downto 0);
        b_M_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_15_out_ap_vld : OUT STD_LOGIC;
        b_M_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_14_out_ap_vld : OUT STD_LOGIC;
        b_M_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_13_out_ap_vld : OUT STD_LOGIC;
        b_M_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_12_out_ap_vld : OUT STD_LOGIC;
        b_M_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_11_out_ap_vld : OUT STD_LOGIC;
        b_M_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_10_out_ap_vld : OUT STD_LOGIC;
        b_M_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_9_out_ap_vld : OUT STD_LOGIC;
        b_M_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_8_out_ap_vld : OUT STD_LOGIC;
        b_M_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_7_out_ap_vld : OUT STD_LOGIC;
        b_M_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_6_out_ap_vld : OUT STD_LOGIC;
        b_M_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_5_out_ap_vld : OUT STD_LOGIC;
        b_M_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_4_out_ap_vld : OUT STD_LOGIC;
        b_M_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_3_out_ap_vld : OUT STD_LOGIC;
        b_M_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_2_out_ap_vld : OUT STD_LOGIC;
        b_M_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_1_out_ap_vld : OUT STD_LOGIC;
        b_M_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_M_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220 : component top_module_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start,
        ap_done => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done,
        ap_idle => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_idle,
        ap_ready => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_ready,
        msg_strm5_dout => msg_strm5_dout,
        msg_strm5_num_data_valid => ap_const_lv16_0,
        msg_strm5_fifo_cap => ap_const_lv16_0,
        msg_strm5_empty_n => msg_strm5_empty_n,
        msg_strm5_read => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_msg_strm5_read,
        trunc_ln => trunc_ln_reg_654,
        blk_strm_din => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din,
        blk_strm_num_data_valid => ap_const_lv14_0,
        blk_strm_fifo_cap => ap_const_lv14_0,
        blk_strm_full_n => blk_strm_full_n,
        blk_strm_write => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_write);

    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229 : component top_module_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start,
        ap_done => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done,
        ap_idle => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_idle,
        ap_ready => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_ready,
        msg_strm5_dout => msg_strm5_dout,
        msg_strm5_num_data_valid => ap_const_lv16_0,
        msg_strm5_fifo_cap => ap_const_lv16_0,
        msg_strm5_empty_n => msg_strm5_empty_n,
        msg_strm5_read => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_msg_strm5_read,
        select_ln375 => select_ln375_reg_683,
        zext_ln375 => trunc_ln1_reg_678,
        trunc_ln299_1 => trunc_ln299_reg_659,
        cmp203 => rev_reg_673,
        b_M_15_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_15_out,
        b_M_15_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_15_out_ap_vld,
        b_M_14_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_14_out,
        b_M_14_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_14_out_ap_vld,
        b_M_13_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_13_out,
        b_M_13_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_13_out_ap_vld,
        b_M_12_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_12_out,
        b_M_12_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_12_out_ap_vld,
        b_M_11_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_11_out,
        b_M_11_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_11_out_ap_vld,
        b_M_10_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_10_out,
        b_M_10_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_10_out_ap_vld,
        b_M_9_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_9_out,
        b_M_9_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_9_out_ap_vld,
        b_M_8_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_8_out,
        b_M_8_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_8_out_ap_vld,
        b_M_7_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_7_out,
        b_M_7_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_7_out_ap_vld,
        b_M_6_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_6_out,
        b_M_6_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_6_out_ap_vld,
        b_M_5_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_5_out,
        b_M_5_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_5_out_ap_vld,
        b_M_4_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_4_out,
        b_M_4_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_4_out_ap_vld,
        b_M_3_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_3_out,
        b_M_3_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_3_out_ap_vld,
        b_M_2_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_2_out,
        b_M_2_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_2_out_ap_vld,
        b_M_1_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_1_out,
        b_M_1_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_1_out_ap_vld,
        b_M_out => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_out,
        b_M_out_ap_vld => grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_ready = ap_const_logic_1)) then 
                    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_logic_1 = ap_NS_fsm_state3))) then 
                    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_ready = ap_const_logic_1)) then 
                    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln343_fu_315_p2 = ap_const_lv1_0))) then
                cmp116_reg_668 <= cmp116_fu_320_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((end_len_strm7_empty_n = ap_const_logic_0) or ((blk_strm_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state9 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9)) or (not(((end_len_strm7_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then
                end_flag_3_reg_211 <= end_len_strm7_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                icmp_ln343_reg_664 <= icmp_ln343_fu_315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                left_reg_641 <= left_fu_264_p1;
                len_reg_634 <= len_strm6_dout;
                trunc_ln299_reg_659 <= trunc_ln299_fu_286_p1;
                trunc_ln485_reg_647 <= trunc_ln485_fu_268_p1;
                trunc_ln_reg_654 <= len_strm6_dout(63 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                rev_reg_673 <= rev_fu_374_p2;
                select_ln375_reg_683 <= select_ln375_fu_391_p3;
                trunc_ln1_reg_678 <= len_reg_634(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (cmp116_reg_668 = ap_const_lv1_0))) then
                tmp_1_reg_688 <= len_reg_634(60 downto 29);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, len_strm6_empty_n, end_len_strm7_empty_n, blk_strm_full_n, nblk_strm8_full_n, end_nblk_strm11_full_n, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state5, icmp_ln343_fu_315_p2, ap_CS_fsm_state8, cmp116_reg_668, grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done, grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done, end_flag_3_reg_211, ap_predicate_op102_write_state9, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((end_len_strm7_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((blk_strm_full_n = ap_const_logic_0) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif ((not(((blk_strm_full_n = ap_const_logic_0) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln343_fu_315_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not((((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_0)) or ((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if ((not(((end_len_strm7_empty_n = ap_const_logic_0) or ((blk_strm_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state9 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, end_len_strm7_empty_n)
    begin
        if (((end_len_strm7_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, end_flag_3_reg_211)
    begin
        if ((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done)
    begin
        if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(blk_strm_full_n, icmp_ln343_fu_315_p2)
    begin
        if (((blk_strm_full_n = ap_const_logic_0) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done)
    begin
        if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(blk_strm_full_n, cmp116_reg_668)
    begin
        if ((((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_0)) or ((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_1)))) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(end_len_strm7_empty_n, blk_strm_full_n, ap_predicate_op102_write_state9)
    begin
        if (((end_len_strm7_empty_n = ap_const_logic_0) or ((blk_strm_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state9 = ap_const_boolean_1)))) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, end_len_strm7_empty_n)
    begin
                ap_block_state1 <= ((end_len_strm7_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, end_flag_3_reg_211)
    begin
                ap_block_state2 <= (((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)));
    end process;


    ap_block_state5_assign_proc : process(blk_strm_full_n, icmp_ln343_fu_315_p2)
    begin
                ap_block_state5 <= ((blk_strm_full_n = ap_const_logic_0) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1));
    end process;


    ap_block_state8_assign_proc : process(blk_strm_full_n, cmp116_reg_668)
    begin
                ap_block_state8 <= (((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_0)) or ((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_1)));
    end process;


    ap_block_state9_assign_proc : process(end_len_strm7_empty_n, blk_strm_full_n, ap_predicate_op102_write_state9)
    begin
                ap_block_state9 <= ((end_len_strm7_empty_n = ap_const_logic_0) or ((blk_strm_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state9 = ap_const_boolean_1)));
    end process;


    ap_condition_355_assign_proc : process(len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
                ap_condition_355 <= (not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2));
    end process;


    ap_done_assign_proc : process(ap_done_reg, len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if ((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op102_write_state9_assign_proc : process(cmp116_reg_668, icmp_ln343_reg_664)
    begin
                ap_predicate_op102_write_state9 <= ((icmp_ln343_reg_664 = ap_const_lv1_0) and (cmp116_reg_668 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;
    blk_num_fu_304_p2 <= std_logic_vector(unsigned(select_ln299_fu_296_p3) + unsigned(zext_ln299_fu_282_p1));

    blk_strm_blk_n_assign_proc : process(blk_strm_full_n, ap_CS_fsm_state9, ap_CS_fsm_state5, icmp_ln343_fu_315_p2, ap_CS_fsm_state8, cmp116_reg_668, icmp_ln343_reg_664)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state8) and (cmp116_reg_668 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (cmp116_reg_668 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln343_reg_664 = ap_const_lv1_0) and (cmp116_reg_668 = ap_const_lv1_0)))) then 
            blk_strm_blk_n <= blk_strm_full_n;
        else 
            blk_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    blk_strm_din_assign_proc : process(end_len_strm7_empty_n, blk_strm_full_n, ap_CS_fsm_state9, ap_CS_fsm_state5, icmp_ln343_fu_315_p2, ap_CS_fsm_state8, cmp116_reg_668, grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din, ap_predicate_op102_write_state9, ap_CS_fsm_state4, or_ln365_1_fu_360_p2, or_ln471_s_fu_447_p17, or_ln467_s_fu_484_p18, or_ln489_s_fu_522_p5)
    begin
        if ((not(((end_len_strm7_empty_n = ap_const_logic_0) or ((blk_strm_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state9 = ap_const_boolean_1)))) and (ap_predicate_op102_write_state9 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            blk_strm_din <= or_ln489_s_fu_522_p5;
        elsif ((not((((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_0)) or ((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (cmp116_reg_668 = ap_const_lv1_1))) then 
            blk_strm_din <= or_ln467_s_fu_484_p18;
        elsif ((not((((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_0)) or ((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (cmp116_reg_668 = ap_const_lv1_0))) then 
            blk_strm_din <= or_ln471_s_fu_447_p17;
        elsif ((not(((blk_strm_full_n = ap_const_logic_0) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1))) then 
            blk_strm_din <= or_ln365_1_fu_360_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            blk_strm_din <= grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din;
        else 
            blk_strm_din <= grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_din;
        end if; 
    end process;


    blk_strm_write_assign_proc : process(end_len_strm7_empty_n, blk_strm_full_n, ap_CS_fsm_state9, ap_CS_fsm_state5, icmp_ln343_fu_315_p2, ap_CS_fsm_state8, cmp116_reg_668, grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_write, ap_predicate_op102_write_state9, ap_CS_fsm_state4)
    begin
        if (((not((((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_0)) or ((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (cmp116_reg_668 = ap_const_lv1_0)) or (not((((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_0)) or ((blk_strm_full_n = ap_const_logic_0) and (cmp116_reg_668 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (cmp116_reg_668 = ap_const_lv1_1)) or (not(((blk_strm_full_n = ap_const_logic_0) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln343_fu_315_p2 = ap_const_lv1_1)) or (not(((end_len_strm7_empty_n = ap_const_logic_0) or ((blk_strm_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state9 = ap_const_boolean_1)))) and (ap_predicate_op102_write_state9 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            blk_strm_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            blk_strm_write <= grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_blk_strm_write;
        else 
            blk_strm_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp116_fu_320_p2 <= "1" when (unsigned(left_reg_641) < unsigned(ap_const_lv6_38)) else "0";

    end_len_strm7_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, end_len_strm7_empty_n, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            end_len_strm7_blk_n <= end_len_strm7_empty_n;
        else 
            end_len_strm7_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    end_len_strm7_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, end_len_strm7_empty_n, blk_strm_full_n, ap_CS_fsm_state9, ap_predicate_op102_write_state9)
    begin
        if (((not(((end_len_strm7_empty_n = ap_const_logic_0) or ((blk_strm_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state9 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9)) or (not(((end_len_strm7_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            end_len_strm7_read <= ap_const_logic_1;
        else 
            end_len_strm7_read <= ap_const_logic_0;
        end if; 
    end process;


    end_nblk_strm11_blk_n_assign_proc : process(end_nblk_strm11_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if ((((end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            end_nblk_strm11_blk_n <= end_nblk_strm11_full_n;
        else 
            end_nblk_strm11_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    end_nblk_strm11_din_assign_proc : process(end_flag_3_reg_211, ap_condition_355)
    begin
        if ((ap_const_boolean_1 = ap_condition_355)) then
            if ((end_flag_3_reg_211 = ap_const_lv1_1)) then 
                end_nblk_strm11_din <= ap_const_lv1_1;
            elsif ((end_flag_3_reg_211 = ap_const_lv1_0)) then 
                end_nblk_strm11_din <= ap_const_lv1_0;
            else 
                end_nblk_strm11_din <= "X";
            end if;
        else 
            end_nblk_strm11_din <= "X";
        end if; 
    end process;


    end_nblk_strm11_write_assign_proc : process(len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if (((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            end_nblk_strm11_write <= ap_const_logic_1;
        else 
            end_nblk_strm11_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_255_p4 <= len_reg_634(60 downto 29);
    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start <= grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_ap_start_reg;
    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start <= grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_ap_start_reg;
    icmp_ln299_fu_290_p2 <= "1" when (unsigned(left_fu_264_p1) > unsigned(ap_const_lv6_37)) else "0";
    icmp_ln343_fu_315_p2 <= "1" when (left_reg_641 = ap_const_lv6_0) else "0";

    internal_ap_ready_assign_proc : process(len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if ((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    left_fu_264_p1 <= len_strm6_dout(6 - 1 downto 0);

    len_strm6_blk_n_assign_proc : process(len_strm6_empty_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if (((end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            len_strm6_blk_n <= len_strm6_empty_n;
        else 
            len_strm6_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    len_strm6_read_assign_proc : process(len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if ((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            len_strm6_read <= ap_const_logic_1;
        else 
            len_strm6_read <= ap_const_logic_0;
        end if; 
    end process;


    msg_strm5_read_assign_proc : process(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_msg_strm5_read, grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_msg_strm5_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            msg_strm5_read <= grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_msg_strm5_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            msg_strm5_read <= grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_220_msg_strm5_read;
        else 
            msg_strm5_read <= ap_const_logic_0;
        end if; 
    end process;


    nblk_strm8_blk_n_assign_proc : process(nblk_strm8_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if (((end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            nblk_strm8_blk_n <= nblk_strm8_full_n;
        else 
            nblk_strm8_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    nblk_strm8_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(blk_num_fu_304_p2),64));

    nblk_strm8_write_assign_proc : process(len_strm6_empty_n, nblk_strm8_full_n, end_nblk_strm11_full_n, ap_CS_fsm_state2, end_flag_3_reg_211)
    begin
        if ((not((((end_flag_3_reg_211 = ap_const_lv1_0) and (end_nblk_strm11_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (nblk_strm8_full_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_0) and (len_strm6_empty_n = ap_const_logic_0)) or ((end_flag_3_reg_211 = ap_const_lv1_1) and (end_nblk_strm11_full_n = ap_const_logic_0)))) and (end_flag_3_reg_211 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            nblk_strm8_write <= ap_const_logic_1;
        else 
            nblk_strm8_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln365_1_fu_360_p2 <= (or_ln365_s_fu_352_p3 or ap_const_lv512_lc_2);
    or_ln365_fu_336_p2 <= (or_ln_fu_325_p5 or ap_const_lv512_lc_2);
    or_ln365_s_fu_352_p3 <= (tmp_24_fu_342_p4 & ap_const_lv32_0);
    or_ln467_s_fu_484_p18 <= ((((((((((((((((trunc_ln485_reg_647 & ap_const_lv3_0) & grp_fu_255_p4) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_13_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_12_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_11_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_10_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_9_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_8_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_7_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_6_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_5_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_4_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_3_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_2_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_1_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_out);
    or_ln471_s_fu_447_p17 <= (((((((((((((((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_15_out & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_14_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_13_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_12_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_11_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_10_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_9_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_8_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_7_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_6_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_5_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_4_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_3_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_2_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_1_out) & grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_PAD_ONE_fu_229_b_M_out);
    or_ln489_s_fu_522_p5 <= (((trunc_ln485_reg_647 & ap_const_lv3_0) & tmp_1_reg_688) & ap_const_lv448_lc_1);
    or_ln_fu_325_p5 <= (((trunc_ln485_reg_647 & ap_const_lv3_0) & grp_fu_255_p4) & ap_const_lv448_lc_1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rev_fu_374_p2 <= (tmp_fu_367_p3 xor ap_const_lv1_1);
    select_ln299_fu_296_p3 <= 
        ap_const_lv59_2 when (icmp_ln299_fu_290_p2(0) = '1') else 
        ap_const_lv59_1;
    select_ln375_fu_391_p3 <= 
        ap_const_lv4_7 when (cmp116_reg_668(0) = '1') else 
        ap_const_lv4_8;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_24_fu_342_p4 <= or_ln365_fu_336_p2(511 downto 32);
    tmp_fu_367_p3 <= len_reg_634(2 downto 2);
    trunc_ln299_fu_286_p1 <= len_strm6_dout(2 - 1 downto 0);
    trunc_ln485_fu_268_p1 <= len_strm6_dout(29 - 1 downto 0);
    trunc_ln_fu_272_p4 <= len_strm6_dout(63 downto 6);
    zext_ln299_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_fu_272_p4),59));
end behav;
