
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtop_module.h"

/*
* The configuration table for devices
*/

XTop_module_Config XTop_module_ConfigTable[XPAR_XTOP_MODULE_NUM_INSTANCES] =
{
	{
		XPAR_TOP_MODULE_0_DEVICE_ID,
		XPAR_TOP_MODULE_0_S_AXI_CONTROL_BASEADDR
	}
};


