// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_module_generic_remainder_float_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    ap_const_lv24_0 = 24'd0;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] x;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] ret_17_fu_194_p1;
reg   [31:0] ret_17_reg_1126;
wire   [0:0] grp_fu_165_p3;
reg   [0:0] p_Result_49_reg_1133;
wire   [0:0] isZ_e_x_V_fu_213_p2;
reg   [0:0] isZ_e_x_V_reg_1139;
wire   [0:0] isF_e_x_V_fu_219_p2;
reg   [0:0] isF_e_x_V_reg_1143;
wire   [0:0] isyBx_1e_V_fu_241_p2;
reg   [0:0] isyBx_1e_V_reg_1147;
wire   [0:0] isyBx_2e_V_fu_257_p2;
reg   [0:0] isyBx_2e_V_reg_1151;
wire   [0:0] isxEy_m_V_fu_263_p2;
reg   [0:0] isxEy_m_V_reg_1155;
wire   [0:0] and_ln414_fu_285_p2;
reg   [0:0] and_ln414_reg_1159;
wire   [31:0] p_Result_55_fu_301_p3;
wire   [0:0] icmp_ln1039_fu_313_p2;
reg   [0:0] icmp_ln1039_reg_1168;
wire  signed [8:0] ret_V_21_fu_563_p2;
reg  signed [8:0] ret_V_21_reg_1194;
wire   [31:0] p_Result_54_fu_592_p4;
wire   [31:0] p_Result_53_fu_602_p3;
wire   [31:0] p_Result_52_fu_610_p3;
reg   [31:0] ap_phi_mux_retval_2_in_phi_fu_147_p16;
reg   [31:0] retval_2_in_reg_144;
wire   [31:0] p_Result_61_fu_1113_p3;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln1027_fu_621_p2;
wire   [0:0] icmp_ln1027_1_fu_734_p2;
wire   [0:0] icmp_ln1019_11_fu_927_p2;
wire   [31:0] p_Result_63_fu_1102_p4;
reg   [24:0] r_sh_V_1_fu_126;
wire   [24:0] r_sh_V_16_fu_671_p3;
wire   [24:0] zext_ln368_fu_573_p1;
reg   [9:0] i_V_fu_130;
wire   [9:0] i_V_3_fu_679_p3;
wire  signed [9:0] sext_ln1496_1_fu_569_p1;
reg   [8:0] loop_V_fu_134;
wire   [8:0] loop_V_2_fu_627_p2;
reg   [31:0] grp_fu_165_p1;
wire   [1:0] grp_fu_178_p4;
wire   [7:0] ret_9_fu_199_p4;
wire   [8:0] zext_ln186_fu_231_p1;
wire   [8:0] ret_V_fu_235_p2;
wire   [7:0] tmp_fu_247_p4;
wire   [22:0] ret_18_fu_209_p1;
wire   [22:0] p_Result_50_fu_269_p1;
wire   [0:0] icmp_ln1019_fu_225_p2;
wire   [8:0] tmp_13_fu_291_p4;
wire   [23:0] p_Result_51_fu_273_p5;
wire   [22:0] trunc_ln628_fu_309_p1;
reg   [22:0] p_Result_s_fu_319_p4;
wire   [23:0] p_Result_56_fu_329_p3;
wire  signed [31:0] sext_ln1198_fu_337_p1;
reg   [31:0] op_assign_fu_341_p3;
wire   [5:0] LZ_V_fu_349_p1;
wire   [6:0] LZ_V_cast_fu_353_p1;
wire   [6:0] p_neg_fu_357_p2;
wire   [4:0] trunc_ln461_fu_367_p1;
wire   [22:0] zext_ln628_fu_377_p1;
wire   [22:0] lshr_ln628_fu_381_p2;
wire   [22:0] p_Result_57_fu_387_p2;
wire   [6:0] add_ln461_fu_371_p2;
wire   [4:0] trunc_ln368_fu_403_p1;
wire   [0:0] icmp_ln368_fu_397_p2;
wire   [4:0] sub_ln368_fu_407_p2;
wire   [4:0] sub_ln368_1_fu_429_p2;
wire   [4:0] select_ln368_1_fu_421_p3;
wire   [4:0] select_ln368_fu_413_p3;
wire   [4:0] select_ln368_2_fu_435_p3;
wire   [24:0] zext_ln186_1_fu_393_p1;
wire   [24:0] zext_ln368_1_fu_443_p1;
wire   [24:0] shl_ln368_fu_455_p2;
reg   [24:0] tmp_15_fu_461_p4;
wire   [24:0] zext_ln368_2_fu_447_p1;
wire   [24:0] zext_ln368_3_fu_451_p1;
wire   [24:0] shl_ln368_1_fu_479_p2;
wire   [24:0] lshr_ln368_fu_485_p2;
wire   [24:0] select_ln368_3_fu_471_p3;
wire   [24:0] and_ln368_fu_491_p2;
wire   [4:0] trunc_ln345_fu_503_p1;
wire   [4:0] sub_ln345_fu_507_p2;
wire   [24:0] zext_ln345_fu_513_p1;
wire   [24:0] lshr_ln345_fu_517_p2;
wire   [24:0] p_Result_58_fu_497_p2;
wire   [24:0] xor_ln345_fu_523_p2;
wire   [24:0] p_Result_59_fu_529_p2;
wire   [23:0] trunc_ln345_1_fu_535_p1;
wire   [23:0] p_Result_60_fu_539_p3;
wire  signed [8:0] sext_ln1496_fu_363_p1;
wire   [8:0] select_ln1019_1_fu_555_p3;
wire   [23:0] ap_mx_V_fu_547_p3;
wire   [24:0] r_sh_V_22_fu_645_p2;
wire   [0:0] icmp_ln1035_fu_633_p2;
wire   [0:0] grp_fu_188_p2;
wire   [0:0] and_ln1031_fu_657_p2;
wire   [24:0] r_sh_V_fu_651_p2;
wire   [24:0] r_sh_V_15_fu_663_p3;
wire   [9:0] i_V_2_fu_639_p2;
wire   [0:0] icmp_ln1019_7_fu_702_p2;
wire   [0:0] and_ln503_fu_708_p2;
wire   [24:0] r_sh_V_5_fu_714_p2;
wire   [24:0] r_sh_V_12_fu_720_p3;
wire   [1:0] tmp_18_fu_739_p4;
wire   [24:0] r_V_fu_728_p2;
wire   [0:0] s_r_V_fu_761_p2;
wire   [1:0] tmp_20_fu_774_p4;
wire   [0:0] icmp_ln1019_9_fu_808_p2;
wire   [0:0] icmp_ln1019_10_fu_822_p2;
wire   [0:0] icmp_ln1027_3_fu_784_p2;
wire   [0:0] and_ln1027_fu_828_p2;
wire   [24:0] r_sh_V_17_fu_790_p2;
wire   [24:0] r_sh_V_19_fu_814_p3;
wire   [0:0] icmp_ln1035_2_fu_796_p2;
wire   [0:0] xor_ln1027_fu_842_p2;
wire   [0:0] and_ln1035_fu_848_p2;
wire   [0:0] and_ln1035_1_fu_854_p2;
wire   [24:0] r_sh_V_18_fu_802_p2;
wire   [24:0] r_sh_V_20_fu_834_p3;
wire   [0:0] icmp_ln1027_2_fu_749_p2;
wire   [0:0] icmp_ln1019_8_fu_755_p2;
wire   [0:0] xor_ln1027_1_fu_868_p2;
wire   [0:0] and_ln1019_fu_874_p2;
wire   [0:0] s_r_V_2_fu_767_p3;
wire   [0:0] s_r_V_3_fu_880_p3;
wire   [0:0] icmp_ln1035_3_fu_896_p2;
wire   [0:0] or_ln1035_fu_902_p2;
wire   [0:0] xor_ln1035_fu_908_p2;
wire   [0:0] or_ln1035_1_fu_914_p2;
wire   [0:0] s_r_V_4_fu_888_p3;
wire   [24:0] r_sh_V_23_fu_860_p3;
reg   [24:0] p_Result_43_fu_936_p4;
wire   [25:0] p_Result_62_fu_946_p3;
wire  signed [31:0] sext_ln1198_1_fu_954_p1;
reg   [31:0] tmp_4_fu_958_p3;
wire   [8:0] trunc_ln841_fu_972_p1;
wire   [8:0] iy_V_fu_976_p2;
wire   [8:0] trunc_ln840_fu_982_p1;
wire   [31:0] zext_ln1669_fu_1006_p1;
wire   [31:0] add_ln534_fu_966_p2;
wire   [31:0] sub_ln1669_fu_1016_p2;
wire   [0:0] icmp_ln1669_fu_1000_p2;
wire   [31:0] shl_ln1669_fu_1010_p2;
wire   [31:0] lshr_ln1669_fu_1022_p2;
wire   [31:0] select_ln1669_fu_1028_p3;
wire   [8:0] iy_V_1_fu_994_p2;
wire   [7:0] trunc_ln840_2_fu_990_p1;
wire   [7:0] trunc_ln840_1_fu_986_p1;
wire   [7:0] add_ln1495_fu_1046_p2;
wire   [24:0] r_V_17_fu_1036_p1;
wire   [7:0] n_V_fu_1058_p2;
wire   [31:0] zext_ln998_fu_1064_p1;
wire   [31:0] zext_ln553_fu_1068_p1;
wire   [0:0] icmp_ln1031_2_fu_1040_p2;
wire   [7:0] fz_exp_V_fu_1052_p2;
wire   [31:0] lshr_ln998_fu_1072_p2;
wire   [22:0] trunc_ln1031_fu_1086_p1;
wire   [22:0] trunc_ln1031_1_fu_1090_p1;
wire   [0:0] s_r_V_6_fu_920_p3;
wire   [7:0] ret_14_fu_1078_p3;
wire   [22:0] fz_sig_V_fu_1094_p3;
wire   [31:0] bitcast_ln356_fu_1122_p1;
reg   [31:0] ap_return_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_condition_134;
reg    ap_condition_142;
reg    ap_condition_152;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_return_preg = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & ((isF_e_x_V_reg_1143 == 1'd1) | ((1'd1 == and_ln414_reg_1159) | ((isyBx_2e_V_reg_1151 == 1'd1) | (((icmp_ln1027_fu_621_p2 == 1'd1) | ((icmp_ln1039_reg_1168 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd1))) | ((isxEy_m_V_reg_1155 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd0)))))))) begin
            ap_return_preg <= bitcast_ln356_fu_1122_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((((icmp_ln1039_fu_313_p2 == 1'd0) & (1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd1)) | ((1'd0 == and_ln414_fu_285_p2) & (isxEy_m_V_fu_263_p2 == 1'd0) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd0))) | ((1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isyBx_1e_V_fu_241_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0))))) begin
        i_V_fu_130 <= sext_ln1496_1_fu_569_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd0)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd0))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd0))))) begin
        i_V_fu_130 <= i_V_3_fu_679_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((((icmp_ln1039_fu_313_p2 == 1'd0) & (1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd1)) | ((1'd0 == and_ln414_fu_285_p2) & (isxEy_m_V_fu_263_p2 == 1'd0) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd0))) | ((1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isyBx_1e_V_fu_241_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0))))) begin
        loop_V_fu_134 <= 9'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd0)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd0))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd0))))) begin
        loop_V_fu_134 <= loop_V_2_fu_627_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((((icmp_ln1039_fu_313_p2 == 1'd0) & (1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd1)) | ((1'd0 == and_ln414_fu_285_p2) & (isxEy_m_V_fu_263_p2 == 1'd0) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd0))) | ((1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isyBx_1e_V_fu_241_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0))))) begin
        r_sh_V_1_fu_126 <= zext_ln368_fu_573_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd0)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd0))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd0))))) begin
        r_sh_V_1_fu_126 <= r_sh_V_16_fu_671_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd1)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd1))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd1))))) begin
        retval_2_in_reg_144 <= ret_17_reg_1126;
    end else if (((ap_start == 1'b1) & (1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd1) & (isF_e_x_V_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        retval_2_in_reg_144 <= ret_17_fu_194_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1019_11_fu_927_p2 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1))))) begin
        retval_2_in_reg_144 <= p_Result_63_fu_1102_p4;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1019_11_fu_927_p2 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1))))) begin
        retval_2_in_reg_144 <= p_Result_61_fu_1113_p3;
    end else if (((ap_start == 1'b1) & (1'd0 == and_ln414_fu_285_p2) & (isxEy_m_V_fu_263_p2 == 1'd1) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isyBx_1e_V_fu_241_p2 == 1'd1) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        retval_2_in_reg_144 <= p_Result_55_fu_301_p3;
    end else if (((ap_start == 1'b1) & (icmp_ln1039_fu_313_p2 == 1'd1) & (1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isyBx_1e_V_fu_241_p2 == 1'd1) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        retval_2_in_reg_144 <= p_Result_54_fu_592_p4;
    end else if (((ap_start == 1'b1) & (1'd1 == and_ln414_fu_285_p2) & (isF_e_x_V_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        retval_2_in_reg_144 <= p_Result_53_fu_602_p3;
    end else if (((ap_start == 1'b1) & (isF_e_x_V_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        retval_2_in_reg_144 <= p_Result_52_fu_610_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((isF_e_x_V_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln414_reg_1159 <= and_ln414_fu_285_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isyBx_1e_V_fu_241_p2 == 1'd1) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln1039_reg_1168 <= icmp_ln1039_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        isF_e_x_V_reg_1143 <= isF_e_x_V_fu_219_p2;
        isZ_e_x_V_reg_1139 <= isZ_e_x_V_fu_213_p2;
        isxEy_m_V_reg_1155 <= isxEy_m_V_fu_263_p2;
        isyBx_1e_V_reg_1147 <= isyBx_1e_V_fu_241_p2;
        isyBx_2e_V_reg_1151 <= isyBx_2e_V_fu_257_p2;
        p_Result_49_reg_1133 <= grp_fu_165_p1[32'd31];
        ret_17_reg_1126 <= ret_17_fu_194_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & ((((icmp_ln1039_fu_313_p2 == 1'd0) & (1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd1)) | ((1'd0 == and_ln414_fu_285_p2) & (isxEy_m_V_fu_263_p2 == 1'd0) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0) & (isZ_e_x_V_fu_213_p2 == 1'd0))) | ((1'd0 == and_ln414_fu_285_p2) & (isyBx_2e_V_fu_257_p2 == 1'd0) & (isyBx_1e_V_fu_241_p2 == 1'd0) & (isF_e_x_V_fu_219_p2 == 1'd0))))) begin
        ret_V_21_reg_1194 <= ret_V_21_fu_563_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & ((isF_e_x_V_reg_1143 == 1'd1) | ((1'd1 == and_ln414_reg_1159) | ((isyBx_2e_V_reg_1151 == 1'd1) | (((icmp_ln1027_fu_621_p2 == 1'd1) | ((icmp_ln1039_reg_1168 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd1))) | ((isxEy_m_V_reg_1155 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd0))))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((1'b1 == ap_condition_152)) begin
            ap_phi_mux_retval_2_in_phi_fu_147_p16 = ret_17_reg_1126;
        end else if ((1'b1 == ap_condition_142)) begin
            ap_phi_mux_retval_2_in_phi_fu_147_p16 = p_Result_63_fu_1102_p4;
        end else if ((1'b1 == ap_condition_134)) begin
            ap_phi_mux_retval_2_in_phi_fu_147_p16 = p_Result_61_fu_1113_p3;
        end else begin
            ap_phi_mux_retval_2_in_phi_fu_147_p16 = retval_2_in_reg_144;
        end
    end else begin
        ap_phi_mux_retval_2_in_phi_fu_147_p16 = retval_2_in_reg_144;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((isF_e_x_V_reg_1143 == 1'd1) | ((1'd1 == and_ln414_reg_1159) | ((isyBx_2e_V_reg_1151 == 1'd1) | (((icmp_ln1027_fu_621_p2 == 1'd1) | ((icmp_ln1039_reg_1168 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd1))) | ((isxEy_m_V_reg_1155 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd0)))))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((isF_e_x_V_reg_1143 == 1'd1) | ((1'd1 == and_ln414_reg_1159) | ((isyBx_2e_V_reg_1151 == 1'd1) | (((icmp_ln1027_fu_621_p2 == 1'd1) | ((icmp_ln1039_reg_1168 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd1))) | ((isxEy_m_V_reg_1155 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd0)))))))) begin
        ap_return = bitcast_ln356_fu_1122_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_165_p1 = ret_17_reg_1126;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_165_p1 = ret_17_fu_194_p1;
    end else begin
        grp_fu_165_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((isF_e_x_V_reg_1143 == 1'd1) | ((1'd1 == and_ln414_reg_1159) | ((isyBx_2e_V_reg_1151 == 1'd1) | (((icmp_ln1027_fu_621_p2 == 1'd1) | ((icmp_ln1039_reg_1168 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd1))) | ((isxEy_m_V_reg_1155 == 1'd1) & (isyBx_1e_V_reg_1147 == 1'd1) & (isZ_e_x_V_reg_1139 == 1'd0)))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LZ_V_cast_fu_353_p1 = LZ_V_fu_349_p1;

assign LZ_V_fu_349_p1 = op_assign_fu_341_p3[5:0];

assign add_ln1495_fu_1046_p2 = (trunc_ln840_2_fu_990_p1 + trunc_ln840_1_fu_986_p1);

assign add_ln461_fu_371_p2 = (LZ_V_cast_fu_353_p1 + 7'd1);

assign add_ln534_fu_966_p2 = ($signed(tmp_4_fu_958_p3) + $signed(32'd4294967295));

assign and_ln1019_fu_874_p2 = (xor_ln1027_1_fu_868_p2 & icmp_ln1019_8_fu_755_p2);

assign and_ln1027_fu_828_p2 = (icmp_ln1027_3_fu_784_p2 & icmp_ln1019_10_fu_822_p2);

assign and_ln1031_fu_657_p2 = (icmp_ln1035_fu_633_p2 & grp_fu_188_p2);

assign and_ln1035_1_fu_854_p2 = (icmp_ln1019_10_fu_822_p2 & and_ln1035_fu_848_p2);

assign and_ln1035_fu_848_p2 = (xor_ln1027_fu_842_p2 & icmp_ln1035_2_fu_796_p2);

assign and_ln368_fu_491_p2 = (shl_ln368_1_fu_479_p2 & lshr_ln368_fu_485_p2);

assign and_ln414_fu_285_p2 = (isxEy_m_V_fu_263_p2 & icmp_ln1019_fu_225_p2);

assign and_ln503_fu_708_p2 = (icmp_ln1019_7_fu_702_p2 & grp_fu_188_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_condition_134 = ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1019_11_fu_927_p2 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_142 = ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1019_11_fu_927_p2 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1019_11_fu_927_p2 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd0) & (icmp_ln1027_fu_621_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_152 = ((((icmp_ln1039_reg_1168 == 1'd0) & (1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd1) & (icmp_ln1027_1_fu_734_p2 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd1)) | ((1'd0 == and_ln414_reg_1159) & (isxEy_m_V_reg_1155 == 1'd0) & (isyBx_2e_V_reg_1151 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (isZ_e_x_V_reg_1139 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd1))) | ((1'd0 == and_ln414_reg_1159) & (isyBx_2e_V_reg_1151 == 1'd0) & (isyBx_1e_V_reg_1147 == 1'd0) & (isF_e_x_V_reg_1143 == 1'd0) & (icmp_ln1027_1_fu_734_p2 == 1'd1) & (icmp_ln1027_fu_621_p2 == 1'd1)));
end

assign ap_mx_V_fu_547_p3 = ((isZ_e_x_V_fu_213_p2[0:0] == 1'b1) ? trunc_ln345_1_fu_535_p1 : p_Result_60_fu_539_p3);

assign bitcast_ln356_fu_1122_p1 = ap_phi_mux_retval_2_in_phi_fu_147_p16;

assign fz_exp_V_fu_1052_p2 = (add_ln1495_fu_1046_p2 + 8'd127);

assign fz_sig_V_fu_1094_p3 = ((icmp_ln1031_2_fu_1040_p2[0:0] == 1'b1) ? trunc_ln1031_fu_1086_p1 : trunc_ln1031_1_fu_1090_p1);

assign grp_fu_165_p3 = grp_fu_165_p1[32'd31];

assign grp_fu_178_p4 = {{r_sh_V_1_fu_126[24:23]}};

assign grp_fu_188_p2 = ((grp_fu_178_p4 != 2'd0) ? 1'b1 : 1'b0);

assign i_V_2_fu_639_p2 = ($signed(i_V_fu_130) + $signed(10'd1023));

assign i_V_3_fu_679_p3 = ((icmp_ln1035_fu_633_p2[0:0] == 1'b1) ? i_V_2_fu_639_p2 : i_V_fu_130);

assign icmp_ln1019_10_fu_822_p2 = ((r_V_fu_728_p2 > 25'd8388608) ? 1'b1 : 1'b0);

assign icmp_ln1019_11_fu_927_p2 = ((r_sh_V_23_fu_860_p3 == 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_7_fu_702_p2 = ((i_V_fu_130 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_8_fu_755_p2 = ((r_V_fu_728_p2 == 25'd8388608) ? 1'b1 : 1'b0);

assign icmp_ln1019_9_fu_808_p2 = ((r_V_fu_728_p2 < 25'd8388609) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_225_p2 = ((ret_9_fu_199_p4 == 8'd135) ? 1'b1 : 1'b0);

assign icmp_ln1027_1_fu_734_p2 = (($signed(ret_V_21_reg_1194) < $signed(9'd511)) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_749_p2 = ((tmp_18_fu_739_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_784_p2 = ((tmp_20_fu_774_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_621_p2 = ((loop_V_fu_134 == 9'd277) ? 1'b1 : 1'b0);

assign icmp_ln1031_2_fu_1040_p2 = (($signed(iy_V_1_fu_994_p2) > $signed(9'd385)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_796_p2 = ((r_sh_V_12_fu_720_p3 > 25'd8388608) ? 1'b1 : 1'b0);

assign icmp_ln1035_3_fu_896_p2 = ((r_sh_V_12_fu_720_p3 != 25'd8388608) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_633_p2 = (($signed(i_V_fu_130) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_313_p2 = ((trunc_ln628_fu_309_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1669_fu_1000_p2 = ((tmp_4_fu_958_p3 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln368_fu_397_p2 = ((add_ln461_fu_371_p2 > 7'd23) ? 1'b1 : 1'b0);

assign isF_e_x_V_fu_219_p2 = ((ret_9_fu_199_p4 == 8'd255) ? 1'b1 : 1'b0);

assign isZ_e_x_V_fu_213_p2 = ((ret_9_fu_199_p4 == 8'd0) ? 1'b1 : 1'b0);

assign isxEy_m_V_fu_263_p2 = ((ret_18_fu_209_p1 == 23'd0) ? 1'b1 : 1'b0);

assign isyBx_1e_V_fu_241_p2 = ((ret_V_fu_235_p2 == 9'd1) ? 1'b1 : 1'b0);

assign isyBx_2e_V_fu_257_p2 = (($signed(tmp_fu_247_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign iy_V_1_fu_994_p2 = (iy_V_fu_976_p2 + trunc_ln840_fu_982_p1);

assign iy_V_fu_976_p2 = (9'd9 - trunc_ln841_fu_972_p1);

assign loop_V_2_fu_627_p2 = (loop_V_fu_134 + 9'd1);

assign lshr_ln1669_fu_1022_p2 = zext_ln1669_fu_1006_p1 >> sub_ln1669_fu_1016_p2;

assign lshr_ln345_fu_517_p2 = 25'd33554431 >> zext_ln345_fu_513_p1;

assign lshr_ln368_fu_485_p2 = 25'd33554431 >> zext_ln368_3_fu_451_p1;

assign lshr_ln628_fu_381_p2 = 23'd8388607 >> zext_ln628_fu_377_p1;

assign lshr_ln998_fu_1072_p2 = zext_ln998_fu_1064_p1 >> zext_ln553_fu_1068_p1;

assign n_V_fu_1058_p2 = ($signed(8'd130) - $signed(add_ln1495_fu_1046_p2));


always @ (sext_ln1198_fu_337_p1) begin
    if (sext_ln1198_fu_337_p1[0] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd0;
    end else if (sext_ln1198_fu_337_p1[1] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd1;
    end else if (sext_ln1198_fu_337_p1[2] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd2;
    end else if (sext_ln1198_fu_337_p1[3] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd3;
    end else if (sext_ln1198_fu_337_p1[4] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd4;
    end else if (sext_ln1198_fu_337_p1[5] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd5;
    end else if (sext_ln1198_fu_337_p1[6] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd6;
    end else if (sext_ln1198_fu_337_p1[7] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd7;
    end else if (sext_ln1198_fu_337_p1[8] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd8;
    end else if (sext_ln1198_fu_337_p1[9] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd9;
    end else if (sext_ln1198_fu_337_p1[10] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd10;
    end else if (sext_ln1198_fu_337_p1[11] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd11;
    end else if (sext_ln1198_fu_337_p1[12] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd12;
    end else if (sext_ln1198_fu_337_p1[13] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd13;
    end else if (sext_ln1198_fu_337_p1[14] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd14;
    end else if (sext_ln1198_fu_337_p1[15] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd15;
    end else if (sext_ln1198_fu_337_p1[16] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd16;
    end else if (sext_ln1198_fu_337_p1[17] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd17;
    end else if (sext_ln1198_fu_337_p1[18] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd18;
    end else if (sext_ln1198_fu_337_p1[19] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd19;
    end else if (sext_ln1198_fu_337_p1[20] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd20;
    end else if (sext_ln1198_fu_337_p1[21] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd21;
    end else if (sext_ln1198_fu_337_p1[22] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd22;
    end else if (sext_ln1198_fu_337_p1[23] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd23;
    end else if (sext_ln1198_fu_337_p1[24] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd24;
    end else if (sext_ln1198_fu_337_p1[25] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd25;
    end else if (sext_ln1198_fu_337_p1[26] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd26;
    end else if (sext_ln1198_fu_337_p1[27] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd27;
    end else if (sext_ln1198_fu_337_p1[28] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd28;
    end else if (sext_ln1198_fu_337_p1[29] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd29;
    end else if (sext_ln1198_fu_337_p1[30] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd30;
    end else if (sext_ln1198_fu_337_p1[31] == 1'b1) begin
        op_assign_fu_341_p3 = 32'd31;
    end else begin
        op_assign_fu_341_p3 = 32'd32;
    end
end

assign or_ln1035_1_fu_914_p2 = (xor_ln1035_fu_908_p2 | icmp_ln1027_2_fu_749_p2);

assign or_ln1035_fu_902_p2 = (icmp_ln1035_3_fu_896_p2 | icmp_ln1019_8_fu_755_p2);

integer ap_tvar_int_0;

always @ (r_sh_V_23_fu_860_p3) begin
    for (ap_tvar_int_0 = 25 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 24 - 0) begin
            p_Result_43_fu_936_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_43_fu_936_p4[ap_tvar_int_0] = r_sh_V_23_fu_860_p3[24 - ap_tvar_int_0];
        end
    end
end

assign p_Result_50_fu_269_p1 = ret_17_fu_194_p1[22:0];

assign p_Result_51_fu_273_p5 = {{p_Result_50_fu_269_p1}, {ap_const_lv24_0[0:0]}};

assign p_Result_52_fu_610_p3 = {{grp_fu_165_p3}, {31'd2147483647}};

assign p_Result_53_fu_602_p3 = {{grp_fu_165_p3}, {31'd0}};

assign p_Result_54_fu_592_p4 = {{{grp_fu_165_p3}, {8'd0}}, {ret_18_fu_209_p1}};

assign p_Result_55_fu_301_p3 = {{tmp_13_fu_291_p4}, {23'd0}};

assign p_Result_56_fu_329_p3 = {{1'd1}, {p_Result_s_fu_319_p4}};

assign p_Result_57_fu_387_p2 = (ret_18_fu_209_p1 & lshr_ln628_fu_381_p2);

assign p_Result_58_fu_497_p2 = (select_ln368_3_fu_471_p3 & and_ln368_fu_491_p2);

assign p_Result_59_fu_529_p2 = (xor_ln345_fu_523_p2 & p_Result_58_fu_497_p2);

assign p_Result_60_fu_539_p3 = {{1'd1}, {ret_18_fu_209_p1}};

assign p_Result_61_fu_1113_p3 = {{s_r_V_6_fu_920_p3}, {31'd0}};

assign p_Result_62_fu_946_p3 = {{1'd1}, {p_Result_43_fu_936_p4}};

assign p_Result_63_fu_1102_p4 = {{{s_r_V_6_fu_920_p3}, {ret_14_fu_1078_p3}}, {fz_sig_V_fu_1094_p3}};

integer ap_tvar_int_1;

always @ (ret_17_fu_194_p1) begin
    for (ap_tvar_int_1 = 23 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 22 - 0) begin
            p_Result_s_fu_319_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_319_p4[ap_tvar_int_1] = ret_17_fu_194_p1[22 - ap_tvar_int_1];
        end
    end
end

assign p_neg_fu_357_p2 = (7'd0 - LZ_V_cast_fu_353_p1);

assign r_V_17_fu_1036_p1 = select_ln1669_fu_1028_p3[24:0];

assign r_V_fu_728_p2 = r_sh_V_12_fu_720_p3 << 25'd1;

assign r_sh_V_12_fu_720_p3 = ((and_ln503_fu_708_p2[0:0] == 1'b1) ? r_sh_V_5_fu_714_p2 : r_sh_V_1_fu_126);

assign r_sh_V_15_fu_663_p3 = ((and_ln1031_fu_657_p2[0:0] == 1'b1) ? r_sh_V_fu_651_p2 : r_sh_V_22_fu_645_p2);

assign r_sh_V_16_fu_671_p3 = ((icmp_ln1035_fu_633_p2[0:0] == 1'b1) ? r_sh_V_15_fu_663_p3 : r_sh_V_1_fu_126);

assign r_sh_V_17_fu_790_p2 = (25'd8388608 - r_sh_V_12_fu_720_p3);

assign r_sh_V_18_fu_802_p2 = ($signed(25'd16777216) - $signed(r_sh_V_12_fu_720_p3));

assign r_sh_V_19_fu_814_p3 = ((icmp_ln1019_9_fu_808_p2[0:0] == 1'b1) ? r_sh_V_12_fu_720_p3 : 25'd8388608);

assign r_sh_V_20_fu_834_p3 = ((and_ln1027_fu_828_p2[0:0] == 1'b1) ? r_sh_V_17_fu_790_p2 : r_sh_V_19_fu_814_p3);

assign r_sh_V_22_fu_645_p2 = r_sh_V_1_fu_126 << 25'd1;

assign r_sh_V_23_fu_860_p3 = ((and_ln1035_1_fu_854_p2[0:0] == 1'b1) ? r_sh_V_18_fu_802_p2 : r_sh_V_20_fu_834_p3);

assign r_sh_V_5_fu_714_p2 = ($signed(r_sh_V_1_fu_126) + $signed(25'd25165824));

assign r_sh_V_fu_651_p2 = (r_sh_V_22_fu_645_p2 ^ 25'd16777216);

assign ret_14_fu_1078_p3 = ((icmp_ln1031_2_fu_1040_p2[0:0] == 1'b1) ? fz_exp_V_fu_1052_p2 : 8'd0);

assign ret_17_fu_194_p1 = x;

assign ret_18_fu_209_p1 = ret_17_fu_194_p1[22:0];

assign ret_9_fu_199_p4 = {{ret_17_fu_194_p1[30:23]}};

assign ret_V_21_fu_563_p2 = ($signed(select_ln1019_1_fu_555_p3) + $signed(9'd377));

assign ret_V_fu_235_p2 = (9'd135 - zext_ln186_fu_231_p1);

assign s_r_V_2_fu_767_p3 = ((and_ln503_fu_708_p2[0:0] == 1'b1) ? s_r_V_fu_761_p2 : p_Result_49_reg_1133);

assign s_r_V_3_fu_880_p3 = ((and_ln1019_fu_874_p2[0:0] == 1'b1) ? s_r_V_2_fu_767_p3 : s_r_V_fu_761_p2);

assign s_r_V_4_fu_888_p3 = ((and_ln1027_fu_828_p2[0:0] == 1'b1) ? s_r_V_fu_761_p2 : s_r_V_3_fu_880_p3);

assign s_r_V_6_fu_920_p3 = ((or_ln1035_1_fu_914_p2[0:0] == 1'b1) ? p_Result_49_reg_1133 : s_r_V_4_fu_888_p3);

assign s_r_V_fu_761_p2 = (grp_fu_165_p3 ^ 1'd1);

assign select_ln1019_1_fu_555_p3 = ((isZ_e_x_V_fu_213_p2[0:0] == 1'b1) ? sext_ln1496_fu_363_p1 : zext_ln186_fu_231_p1);

assign select_ln1669_fu_1028_p3 = ((icmp_ln1669_fu_1000_p2[0:0] == 1'b1) ? shl_ln1669_fu_1010_p2 : lshr_ln1669_fu_1022_p2);

assign select_ln368_1_fu_421_p3 = ((icmp_ln368_fu_397_p2[0:0] == 1'b1) ? sub_ln368_fu_407_p2 : trunc_ln368_fu_403_p1);

assign select_ln368_2_fu_435_p3 = ((icmp_ln368_fu_397_p2[0:0] == 1'b1) ? sub_ln368_1_fu_429_p2 : 5'd1);

assign select_ln368_3_fu_471_p3 = ((icmp_ln368_fu_397_p2[0:0] == 1'b1) ? tmp_15_fu_461_p4 : shl_ln368_fu_455_p2);

assign select_ln368_fu_413_p3 = ((icmp_ln368_fu_397_p2[0:0] == 1'b1) ? 5'd23 : trunc_ln368_fu_403_p1);

assign sext_ln1198_1_fu_954_p1 = $signed(p_Result_62_fu_946_p3);

assign sext_ln1198_fu_337_p1 = $signed(p_Result_56_fu_329_p3);

assign sext_ln1496_1_fu_569_p1 = ret_V_21_fu_563_p2;

assign sext_ln1496_fu_363_p1 = $signed(p_neg_fu_357_p2);

assign shl_ln1669_fu_1010_p2 = zext_ln1669_fu_1006_p1 << add_ln534_fu_966_p2;

assign shl_ln368_1_fu_479_p2 = 25'd33554431 << zext_ln368_2_fu_447_p1;

assign shl_ln368_fu_455_p2 = zext_ln186_1_fu_393_p1 << zext_ln368_1_fu_443_p1;

assign sub_ln1669_fu_1016_p2 = (32'd1 - tmp_4_fu_958_p3);

assign sub_ln345_fu_507_p2 = ($signed(5'd24) - $signed(trunc_ln345_fu_503_p1));

assign sub_ln368_1_fu_429_p2 = ($signed(5'd24) - $signed(trunc_ln368_fu_403_p1));

assign sub_ln368_fu_407_p2 = ($signed(5'd24) - $signed(trunc_ln368_fu_403_p1));

assign tmp_13_fu_291_p4 = {{ret_17_fu_194_p1[31:23]}};

integer ap_tvar_int_2;

always @ (shl_ln368_fu_455_p2) begin
    for (ap_tvar_int_2 = 25 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 24 - 0) begin
            tmp_15_fu_461_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_15_fu_461_p4[ap_tvar_int_2] = shl_ln368_fu_455_p2[24 - ap_tvar_int_2];
        end
    end
end

assign tmp_18_fu_739_p4 = {{r_sh_V_12_fu_720_p3[23:22]}};

assign tmp_20_fu_774_p4 = {{r_sh_V_12_fu_720_p3[24:23]}};


always @ (sext_ln1198_1_fu_954_p1) begin
    if (sext_ln1198_1_fu_954_p1[0] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd0;
    end else if (sext_ln1198_1_fu_954_p1[1] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd1;
    end else if (sext_ln1198_1_fu_954_p1[2] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd2;
    end else if (sext_ln1198_1_fu_954_p1[3] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd3;
    end else if (sext_ln1198_1_fu_954_p1[4] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd4;
    end else if (sext_ln1198_1_fu_954_p1[5] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd5;
    end else if (sext_ln1198_1_fu_954_p1[6] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd6;
    end else if (sext_ln1198_1_fu_954_p1[7] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd7;
    end else if (sext_ln1198_1_fu_954_p1[8] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd8;
    end else if (sext_ln1198_1_fu_954_p1[9] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd9;
    end else if (sext_ln1198_1_fu_954_p1[10] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd10;
    end else if (sext_ln1198_1_fu_954_p1[11] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd11;
    end else if (sext_ln1198_1_fu_954_p1[12] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd12;
    end else if (sext_ln1198_1_fu_954_p1[13] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd13;
    end else if (sext_ln1198_1_fu_954_p1[14] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd14;
    end else if (sext_ln1198_1_fu_954_p1[15] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd15;
    end else if (sext_ln1198_1_fu_954_p1[16] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd16;
    end else if (sext_ln1198_1_fu_954_p1[17] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd17;
    end else if (sext_ln1198_1_fu_954_p1[18] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd18;
    end else if (sext_ln1198_1_fu_954_p1[19] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd19;
    end else if (sext_ln1198_1_fu_954_p1[20] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd20;
    end else if (sext_ln1198_1_fu_954_p1[21] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd21;
    end else if (sext_ln1198_1_fu_954_p1[22] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd22;
    end else if (sext_ln1198_1_fu_954_p1[23] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd23;
    end else if (sext_ln1198_1_fu_954_p1[24] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd24;
    end else if (sext_ln1198_1_fu_954_p1[25] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd25;
    end else if (sext_ln1198_1_fu_954_p1[26] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd26;
    end else if (sext_ln1198_1_fu_954_p1[27] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd27;
    end else if (sext_ln1198_1_fu_954_p1[28] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd28;
    end else if (sext_ln1198_1_fu_954_p1[29] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd29;
    end else if (sext_ln1198_1_fu_954_p1[30] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd30;
    end else if (sext_ln1198_1_fu_954_p1[31] == 1'b1) begin
        tmp_4_fu_958_p3 = 32'd31;
    end else begin
        tmp_4_fu_958_p3 = 32'd32;
    end
end

assign tmp_fu_247_p4 = {{ret_V_fu_235_p2[8:1]}};

assign trunc_ln1031_1_fu_1090_p1 = lshr_ln998_fu_1072_p2[22:0];

assign trunc_ln1031_fu_1086_p1 = select_ln1669_fu_1028_p3[22:0];

assign trunc_ln345_1_fu_535_p1 = p_Result_59_fu_529_p2[23:0];

assign trunc_ln345_fu_503_p1 = op_assign_fu_341_p3[4:0];

assign trunc_ln368_fu_403_p1 = add_ln461_fu_371_p2[4:0];

assign trunc_ln461_fu_367_p1 = op_assign_fu_341_p3[4:0];

assign trunc_ln628_fu_309_p1 = p_Result_51_fu_273_p5[22:0];

assign trunc_ln840_1_fu_986_p1 = i_V_fu_130[7:0];

assign trunc_ln840_2_fu_990_p1 = iy_V_fu_976_p2[7:0];

assign trunc_ln840_fu_982_p1 = i_V_fu_130[8:0];

assign trunc_ln841_fu_972_p1 = tmp_4_fu_958_p3[8:0];

assign xor_ln1027_1_fu_868_p2 = (icmp_ln1027_2_fu_749_p2 ^ 1'd1);

assign xor_ln1027_fu_842_p2 = (icmp_ln1027_3_fu_784_p2 ^ 1'd1);

assign xor_ln1035_fu_908_p2 = (or_ln1035_fu_902_p2 ^ 1'd1);

assign xor_ln345_fu_523_p2 = (lshr_ln345_fu_517_p2 ^ 25'd16777215);

assign zext_ln1669_fu_1006_p1 = r_sh_V_23_fu_860_p3;

assign zext_ln186_1_fu_393_p1 = p_Result_57_fu_387_p2;

assign zext_ln186_fu_231_p1 = ret_9_fu_199_p4;

assign zext_ln345_fu_513_p1 = sub_ln345_fu_507_p2;

assign zext_ln368_1_fu_443_p1 = select_ln368_1_fu_421_p3;

assign zext_ln368_2_fu_447_p1 = select_ln368_fu_413_p3;

assign zext_ln368_3_fu_451_p1 = select_ln368_2_fu_435_p3;

assign zext_ln368_fu_573_p1 = ap_mx_V_fu_547_p3;

assign zext_ln553_fu_1068_p1 = n_V_fu_1058_p2;

assign zext_ln628_fu_377_p1 = trunc_ln461_fu_367_p1;

assign zext_ln998_fu_1064_p1 = r_V_17_fu_1036_p1;

endmodule //top_module_generic_remainder_float_s
