// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_module_sha256_top_64_256_s (
        msg_strm5_dout,
        msg_strm5_empty_n,
        msg_strm5_read,
        len_strm6_dout,
        len_strm6_empty_n,
        len_strm6_read,
        end_len_strm7_dout,
        end_len_strm7_empty_n,
        end_len_strm7_read,
        hash_strm8_din,
        hash_strm8_full_n,
        hash_strm8_write,
        end_hash_strm9_din,
        end_hash_strm9_full_n,
        end_hash_strm9_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] msg_strm5_dout;
input   msg_strm5_empty_n;
output   msg_strm5_read;
input  [63:0] len_strm6_dout;
input   len_strm6_empty_n;
output   len_strm6_read;
input  [0:0] end_len_strm7_dout;
input   end_len_strm7_empty_n;
output   end_len_strm7_read;
output  [255:0] hash_strm8_din;
input   hash_strm8_full_n;
output   hash_strm8_write;
output  [0:0] end_hash_strm9_din;
input   end_hash_strm9_full_n;
output   end_hash_strm9_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    preProcessing_U0_ap_start;
wire    preProcessing_U0_start_full_n;
wire    preProcessing_U0_ap_done;
wire    preProcessing_U0_ap_continue;
wire    preProcessing_U0_ap_idle;
wire    preProcessing_U0_ap_ready;
wire    preProcessing_U0_start_out;
wire    preProcessing_U0_start_write;
wire    preProcessing_U0_msg_strm5_read;
wire    preProcessing_U0_len_strm6_read;
wire    preProcessing_U0_end_len_strm7_read;
wire   [511:0] preProcessing_U0_blk_strm_din;
wire    preProcessing_U0_blk_strm_write;
wire   [63:0] preProcessing_U0_nblk_strm8_din;
wire    preProcessing_U0_nblk_strm8_write;
wire   [0:0] preProcessing_U0_end_nblk_strm11_din;
wire    preProcessing_U0_end_nblk_strm11_write;
wire    dup_strm_U0_ap_start;
wire    dup_strm_U0_ap_done;
wire    dup_strm_U0_ap_continue;
wire    dup_strm_U0_ap_idle;
wire    dup_strm_U0_ap_ready;
wire    dup_strm_U0_start_out;
wire    dup_strm_U0_start_write;
wire    dup_strm_U0_nblk_strm8_read;
wire    dup_strm_U0_end_nblk_strm11_read;
wire   [63:0] dup_strm_U0_nblk_strm19_din;
wire    dup_strm_U0_nblk_strm19_write;
wire   [0:0] dup_strm_U0_end_nblk_strm112_din;
wire    dup_strm_U0_end_nblk_strm112_write;
wire   [63:0] dup_strm_U0_nblk_strm210_din;
wire    dup_strm_U0_nblk_strm210_write;
wire   [0:0] dup_strm_U0_end_nblk_strm213_din;
wire    dup_strm_U0_end_nblk_strm213_write;
wire    generateMsgSchedule_U0_ap_start;
wire    generateMsgSchedule_U0_ap_done;
wire    generateMsgSchedule_U0_ap_continue;
wire    generateMsgSchedule_U0_ap_idle;
wire    generateMsgSchedule_U0_ap_ready;
wire    generateMsgSchedule_U0_blk_strm_read;
wire    generateMsgSchedule_U0_nblk_strm19_read;
wire    generateMsgSchedule_U0_end_nblk_strm112_read;
wire   [31:0] generateMsgSchedule_U0_w_strm14_din;
wire    generateMsgSchedule_U0_w_strm14_write;
wire    sha256Digest_256_U0_ap_start;
wire    sha256Digest_256_U0_ap_done;
wire    sha256Digest_256_U0_ap_continue;
wire    sha256Digest_256_U0_ap_idle;
wire    sha256Digest_256_U0_ap_ready;
wire    sha256Digest_256_U0_nblk_strm210_read;
wire    sha256Digest_256_U0_end_nblk_strm213_read;
wire    sha256Digest_256_U0_w_strm14_read;
wire   [255:0] sha256Digest_256_U0_hash_strm8_din;
wire    sha256Digest_256_U0_hash_strm8_write;
wire   [0:0] sha256Digest_256_U0_end_hash_strm9_din;
wire    sha256Digest_256_U0_end_hash_strm9_write;
wire    blk_strm_full_n;
wire   [511:0] blk_strm_dout;
wire   [13:0] blk_strm_num_data_valid;
wire   [13:0] blk_strm_fifo_cap;
wire    blk_strm_empty_n;
wire    nblk_strm_full_n;
wire   [63:0] nblk_strm_dout;
wire   [5:0] nblk_strm_num_data_valid;
wire   [5:0] nblk_strm_fifo_cap;
wire    nblk_strm_empty_n;
wire    end_nblk_strm_full_n;
wire   [0:0] end_nblk_strm_dout;
wire   [5:0] end_nblk_strm_num_data_valid;
wire   [5:0] end_nblk_strm_fifo_cap;
wire    end_nblk_strm_empty_n;
wire    nblk_strm1_full_n;
wire   [63:0] nblk_strm1_dout;
wire   [5:0] nblk_strm1_num_data_valid;
wire   [5:0] nblk_strm1_fifo_cap;
wire    nblk_strm1_empty_n;
wire    end_nblk_strm1_full_n;
wire   [0:0] end_nblk_strm1_dout;
wire   [5:0] end_nblk_strm1_num_data_valid;
wire   [5:0] end_nblk_strm1_fifo_cap;
wire    end_nblk_strm1_empty_n;
wire    nblk_strm2_full_n;
wire   [63:0] nblk_strm2_dout;
wire   [5:0] nblk_strm2_num_data_valid;
wire   [5:0] nblk_strm2_fifo_cap;
wire    nblk_strm2_empty_n;
wire    end_nblk_strm2_full_n;
wire   [0:0] end_nblk_strm2_dout;
wire   [5:0] end_nblk_strm2_num_data_valid;
wire   [5:0] end_nblk_strm2_fifo_cap;
wire    end_nblk_strm2_empty_n;
wire    w_strm_full_n;
wire   [31:0] w_strm_dout;
wire   [5:0] w_strm_num_data_valid;
wire   [5:0] w_strm_fifo_cap;
wire    w_strm_empty_n;
wire   [0:0] start_for_dup_strm_U0_din;
wire    start_for_dup_strm_U0_full_n;
wire   [0:0] start_for_dup_strm_U0_dout;
wire    start_for_dup_strm_U0_empty_n;
wire   [0:0] start_for_generateMsgSchedule_U0_din;
wire    start_for_generateMsgSchedule_U0_full_n;
wire   [0:0] start_for_generateMsgSchedule_U0_dout;
wire    start_for_generateMsgSchedule_U0_empty_n;
wire   [0:0] start_for_sha256Digest_256_U0_din;
wire    start_for_sha256Digest_256_U0_full_n;
wire   [0:0] start_for_sha256Digest_256_U0_dout;
wire    start_for_sha256Digest_256_U0_empty_n;

top_module_preProcessing preProcessing_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(preProcessing_U0_ap_start),
    .start_full_n(preProcessing_U0_start_full_n),
    .ap_done(preProcessing_U0_ap_done),
    .ap_continue(preProcessing_U0_ap_continue),
    .ap_idle(preProcessing_U0_ap_idle),
    .ap_ready(preProcessing_U0_ap_ready),
    .start_out(preProcessing_U0_start_out),
    .start_write(preProcessing_U0_start_write),
    .msg_strm5_dout(msg_strm5_dout),
    .msg_strm5_num_data_valid(16'd0),
    .msg_strm5_fifo_cap(16'd0),
    .msg_strm5_empty_n(msg_strm5_empty_n),
    .msg_strm5_read(preProcessing_U0_msg_strm5_read),
    .len_strm6_dout(len_strm6_dout),
    .len_strm6_num_data_valid(2'd0),
    .len_strm6_fifo_cap(2'd0),
    .len_strm6_empty_n(len_strm6_empty_n),
    .len_strm6_read(preProcessing_U0_len_strm6_read),
    .end_len_strm7_dout(end_len_strm7_dout),
    .end_len_strm7_num_data_valid(2'd0),
    .end_len_strm7_fifo_cap(2'd0),
    .end_len_strm7_empty_n(end_len_strm7_empty_n),
    .end_len_strm7_read(preProcessing_U0_end_len_strm7_read),
    .blk_strm_din(preProcessing_U0_blk_strm_din),
    .blk_strm_num_data_valid(blk_strm_num_data_valid),
    .blk_strm_fifo_cap(blk_strm_fifo_cap),
    .blk_strm_full_n(blk_strm_full_n),
    .blk_strm_write(preProcessing_U0_blk_strm_write),
    .nblk_strm8_din(preProcessing_U0_nblk_strm8_din),
    .nblk_strm8_num_data_valid(nblk_strm_num_data_valid),
    .nblk_strm8_fifo_cap(nblk_strm_fifo_cap),
    .nblk_strm8_full_n(nblk_strm_full_n),
    .nblk_strm8_write(preProcessing_U0_nblk_strm8_write),
    .end_nblk_strm11_din(preProcessing_U0_end_nblk_strm11_din),
    .end_nblk_strm11_num_data_valid(end_nblk_strm_num_data_valid),
    .end_nblk_strm11_fifo_cap(end_nblk_strm_fifo_cap),
    .end_nblk_strm11_full_n(end_nblk_strm_full_n),
    .end_nblk_strm11_write(preProcessing_U0_end_nblk_strm11_write)
);

top_module_dup_strm dup_strm_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dup_strm_U0_ap_start),
    .start_full_n(start_for_sha256Digest_256_U0_full_n),
    .ap_done(dup_strm_U0_ap_done),
    .ap_continue(dup_strm_U0_ap_continue),
    .ap_idle(dup_strm_U0_ap_idle),
    .ap_ready(dup_strm_U0_ap_ready),
    .start_out(dup_strm_U0_start_out),
    .start_write(dup_strm_U0_start_write),
    .nblk_strm8_dout(nblk_strm_dout),
    .nblk_strm8_num_data_valid(nblk_strm_num_data_valid),
    .nblk_strm8_fifo_cap(nblk_strm_fifo_cap),
    .nblk_strm8_empty_n(nblk_strm_empty_n),
    .nblk_strm8_read(dup_strm_U0_nblk_strm8_read),
    .end_nblk_strm11_dout(end_nblk_strm_dout),
    .end_nblk_strm11_num_data_valid(end_nblk_strm_num_data_valid),
    .end_nblk_strm11_fifo_cap(end_nblk_strm_fifo_cap),
    .end_nblk_strm11_empty_n(end_nblk_strm_empty_n),
    .end_nblk_strm11_read(dup_strm_U0_end_nblk_strm11_read),
    .nblk_strm19_din(dup_strm_U0_nblk_strm19_din),
    .nblk_strm19_num_data_valid(nblk_strm1_num_data_valid),
    .nblk_strm19_fifo_cap(nblk_strm1_fifo_cap),
    .nblk_strm19_full_n(nblk_strm1_full_n),
    .nblk_strm19_write(dup_strm_U0_nblk_strm19_write),
    .end_nblk_strm112_din(dup_strm_U0_end_nblk_strm112_din),
    .end_nblk_strm112_num_data_valid(end_nblk_strm1_num_data_valid),
    .end_nblk_strm112_fifo_cap(end_nblk_strm1_fifo_cap),
    .end_nblk_strm112_full_n(end_nblk_strm1_full_n),
    .end_nblk_strm112_write(dup_strm_U0_end_nblk_strm112_write),
    .nblk_strm210_din(dup_strm_U0_nblk_strm210_din),
    .nblk_strm210_num_data_valid(nblk_strm2_num_data_valid),
    .nblk_strm210_fifo_cap(nblk_strm2_fifo_cap),
    .nblk_strm210_full_n(nblk_strm2_full_n),
    .nblk_strm210_write(dup_strm_U0_nblk_strm210_write),
    .end_nblk_strm213_din(dup_strm_U0_end_nblk_strm213_din),
    .end_nblk_strm213_num_data_valid(end_nblk_strm2_num_data_valid),
    .end_nblk_strm213_fifo_cap(end_nblk_strm2_fifo_cap),
    .end_nblk_strm213_full_n(end_nblk_strm2_full_n),
    .end_nblk_strm213_write(dup_strm_U0_end_nblk_strm213_write)
);

top_module_generateMsgSchedule generateMsgSchedule_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(generateMsgSchedule_U0_ap_start),
    .ap_done(generateMsgSchedule_U0_ap_done),
    .ap_continue(generateMsgSchedule_U0_ap_continue),
    .ap_idle(generateMsgSchedule_U0_ap_idle),
    .ap_ready(generateMsgSchedule_U0_ap_ready),
    .blk_strm_dout(blk_strm_dout),
    .blk_strm_num_data_valid(blk_strm_num_data_valid),
    .blk_strm_fifo_cap(blk_strm_fifo_cap),
    .blk_strm_empty_n(blk_strm_empty_n),
    .blk_strm_read(generateMsgSchedule_U0_blk_strm_read),
    .nblk_strm19_dout(nblk_strm1_dout),
    .nblk_strm19_num_data_valid(nblk_strm1_num_data_valid),
    .nblk_strm19_fifo_cap(nblk_strm1_fifo_cap),
    .nblk_strm19_empty_n(nblk_strm1_empty_n),
    .nblk_strm19_read(generateMsgSchedule_U0_nblk_strm19_read),
    .end_nblk_strm112_dout(end_nblk_strm1_dout),
    .end_nblk_strm112_num_data_valid(end_nblk_strm1_num_data_valid),
    .end_nblk_strm112_fifo_cap(end_nblk_strm1_fifo_cap),
    .end_nblk_strm112_empty_n(end_nblk_strm1_empty_n),
    .end_nblk_strm112_read(generateMsgSchedule_U0_end_nblk_strm112_read),
    .w_strm14_din(generateMsgSchedule_U0_w_strm14_din),
    .w_strm14_num_data_valid(w_strm_num_data_valid),
    .w_strm14_fifo_cap(w_strm_fifo_cap),
    .w_strm14_full_n(w_strm_full_n),
    .w_strm14_write(generateMsgSchedule_U0_w_strm14_write)
);

top_module_sha256Digest_256_s sha256Digest_256_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sha256Digest_256_U0_ap_start),
    .ap_done(sha256Digest_256_U0_ap_done),
    .ap_continue(sha256Digest_256_U0_ap_continue),
    .ap_idle(sha256Digest_256_U0_ap_idle),
    .ap_ready(sha256Digest_256_U0_ap_ready),
    .nblk_strm210_dout(nblk_strm2_dout),
    .nblk_strm210_num_data_valid(nblk_strm2_num_data_valid),
    .nblk_strm210_fifo_cap(nblk_strm2_fifo_cap),
    .nblk_strm210_empty_n(nblk_strm2_empty_n),
    .nblk_strm210_read(sha256Digest_256_U0_nblk_strm210_read),
    .end_nblk_strm213_dout(end_nblk_strm2_dout),
    .end_nblk_strm213_num_data_valid(end_nblk_strm2_num_data_valid),
    .end_nblk_strm213_fifo_cap(end_nblk_strm2_fifo_cap),
    .end_nblk_strm213_empty_n(end_nblk_strm2_empty_n),
    .end_nblk_strm213_read(sha256Digest_256_U0_end_nblk_strm213_read),
    .w_strm14_dout(w_strm_dout),
    .w_strm14_num_data_valid(w_strm_num_data_valid),
    .w_strm14_fifo_cap(w_strm_fifo_cap),
    .w_strm14_empty_n(w_strm_empty_n),
    .w_strm14_read(sha256Digest_256_U0_w_strm14_read),
    .hash_strm8_din(sha256Digest_256_U0_hash_strm8_din),
    .hash_strm8_num_data_valid(2'd0),
    .hash_strm8_fifo_cap(2'd0),
    .hash_strm8_full_n(hash_strm8_full_n),
    .hash_strm8_write(sha256Digest_256_U0_hash_strm8_write),
    .end_hash_strm9_din(sha256Digest_256_U0_end_hash_strm9_din),
    .end_hash_strm9_num_data_valid(2'd0),
    .end_hash_strm9_fifo_cap(2'd0),
    .end_hash_strm9_full_n(end_hash_strm9_full_n),
    .end_hash_strm9_write(sha256Digest_256_U0_end_hash_strm9_write)
);

top_module_fifo_w512_d4097_D blk_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(preProcessing_U0_blk_strm_din),
    .if_full_n(blk_strm_full_n),
    .if_write(preProcessing_U0_blk_strm_write),
    .if_dout(blk_strm_dout),
    .if_num_data_valid(blk_strm_num_data_valid),
    .if_fifo_cap(blk_strm_fifo_cap),
    .if_empty_n(blk_strm_empty_n),
    .if_read(generateMsgSchedule_U0_blk_strm_read)
);

top_module_fifo_w64_d32_D nblk_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(preProcessing_U0_nblk_strm8_din),
    .if_full_n(nblk_strm_full_n),
    .if_write(preProcessing_U0_nblk_strm8_write),
    .if_dout(nblk_strm_dout),
    .if_num_data_valid(nblk_strm_num_data_valid),
    .if_fifo_cap(nblk_strm_fifo_cap),
    .if_empty_n(nblk_strm_empty_n),
    .if_read(dup_strm_U0_nblk_strm8_read)
);

top_module_fifo_w1_d32_D end_nblk_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(preProcessing_U0_end_nblk_strm11_din),
    .if_full_n(end_nblk_strm_full_n),
    .if_write(preProcessing_U0_end_nblk_strm11_write),
    .if_dout(end_nblk_strm_dout),
    .if_num_data_valid(end_nblk_strm_num_data_valid),
    .if_fifo_cap(end_nblk_strm_fifo_cap),
    .if_empty_n(end_nblk_strm_empty_n),
    .if_read(dup_strm_U0_end_nblk_strm11_read)
);

top_module_fifo_w64_d32_D nblk_strm1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_nblk_strm19_din),
    .if_full_n(nblk_strm1_full_n),
    .if_write(dup_strm_U0_nblk_strm19_write),
    .if_dout(nblk_strm1_dout),
    .if_num_data_valid(nblk_strm1_num_data_valid),
    .if_fifo_cap(nblk_strm1_fifo_cap),
    .if_empty_n(nblk_strm1_empty_n),
    .if_read(generateMsgSchedule_U0_nblk_strm19_read)
);

top_module_fifo_w1_d32_D end_nblk_strm1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_end_nblk_strm112_din),
    .if_full_n(end_nblk_strm1_full_n),
    .if_write(dup_strm_U0_end_nblk_strm112_write),
    .if_dout(end_nblk_strm1_dout),
    .if_num_data_valid(end_nblk_strm1_num_data_valid),
    .if_fifo_cap(end_nblk_strm1_fifo_cap),
    .if_empty_n(end_nblk_strm1_empty_n),
    .if_read(generateMsgSchedule_U0_end_nblk_strm112_read)
);

top_module_fifo_w64_d32_D nblk_strm2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_nblk_strm210_din),
    .if_full_n(nblk_strm2_full_n),
    .if_write(dup_strm_U0_nblk_strm210_write),
    .if_dout(nblk_strm2_dout),
    .if_num_data_valid(nblk_strm2_num_data_valid),
    .if_fifo_cap(nblk_strm2_fifo_cap),
    .if_empty_n(nblk_strm2_empty_n),
    .if_read(sha256Digest_256_U0_nblk_strm210_read)
);

top_module_fifo_w1_d32_D end_nblk_strm2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_end_nblk_strm213_din),
    .if_full_n(end_nblk_strm2_full_n),
    .if_write(dup_strm_U0_end_nblk_strm213_write),
    .if_dout(end_nblk_strm2_dout),
    .if_num_data_valid(end_nblk_strm2_num_data_valid),
    .if_fifo_cap(end_nblk_strm2_fifo_cap),
    .if_empty_n(end_nblk_strm2_empty_n),
    .if_read(sha256Digest_256_U0_end_nblk_strm213_read)
);

top_module_fifo_w32_d32_D w_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(generateMsgSchedule_U0_w_strm14_din),
    .if_full_n(w_strm_full_n),
    .if_write(generateMsgSchedule_U0_w_strm14_write),
    .if_dout(w_strm_dout),
    .if_num_data_valid(w_strm_num_data_valid),
    .if_fifo_cap(w_strm_fifo_cap),
    .if_empty_n(w_strm_empty_n),
    .if_read(sha256Digest_256_U0_w_strm14_read)
);

top_module_start_for_dup_strm_U0 start_for_dup_strm_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dup_strm_U0_din),
    .if_full_n(start_for_dup_strm_U0_full_n),
    .if_write(preProcessing_U0_start_write),
    .if_dout(start_for_dup_strm_U0_dout),
    .if_empty_n(start_for_dup_strm_U0_empty_n),
    .if_read(dup_strm_U0_ap_ready)
);

top_module_start_for_generateMsgSchedule_U0 start_for_generateMsgSchedule_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_generateMsgSchedule_U0_din),
    .if_full_n(start_for_generateMsgSchedule_U0_full_n),
    .if_write(preProcessing_U0_start_write),
    .if_dout(start_for_generateMsgSchedule_U0_dout),
    .if_empty_n(start_for_generateMsgSchedule_U0_empty_n),
    .if_read(generateMsgSchedule_U0_ap_ready)
);

top_module_start_for_sha256Digest_256_U0 start_for_sha256Digest_256_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sha256Digest_256_U0_din),
    .if_full_n(start_for_sha256Digest_256_U0_full_n),
    .if_write(dup_strm_U0_start_write),
    .if_dout(start_for_sha256Digest_256_U0_dout),
    .if_empty_n(start_for_sha256Digest_256_U0_empty_n),
    .if_read(sha256Digest_256_U0_ap_ready)
);

assign ap_done = sha256Digest_256_U0_ap_done;

assign ap_idle = (sha256Digest_256_U0_ap_idle & preProcessing_U0_ap_idle & generateMsgSchedule_U0_ap_idle & dup_strm_U0_ap_idle);

assign ap_ready = preProcessing_U0_ap_ready;

assign dup_strm_U0_ap_continue = 1'b1;

assign dup_strm_U0_ap_start = start_for_dup_strm_U0_empty_n;

assign end_hash_strm9_din = sha256Digest_256_U0_end_hash_strm9_din;

assign end_hash_strm9_write = sha256Digest_256_U0_end_hash_strm9_write;

assign end_len_strm7_read = preProcessing_U0_end_len_strm7_read;

assign generateMsgSchedule_U0_ap_continue = 1'b1;

assign generateMsgSchedule_U0_ap_start = start_for_generateMsgSchedule_U0_empty_n;

assign hash_strm8_din = sha256Digest_256_U0_hash_strm8_din;

assign hash_strm8_write = sha256Digest_256_U0_hash_strm8_write;

assign len_strm6_read = preProcessing_U0_len_strm6_read;

assign msg_strm5_read = preProcessing_U0_msg_strm5_read;

assign preProcessing_U0_ap_continue = 1'b1;

assign preProcessing_U0_ap_start = ap_start;

assign preProcessing_U0_start_full_n = (start_for_generateMsgSchedule_U0_full_n & start_for_dup_strm_U0_full_n);

assign sha256Digest_256_U0_ap_continue = ap_continue;

assign sha256Digest_256_U0_ap_start = start_for_sha256Digest_256_U0_empty_n;

assign start_for_dup_strm_U0_din = 1'b1;

assign start_for_generateMsgSchedule_U0_din = 1'b1;

assign start_for_sha256Digest_256_U0_din = 1'b1;

endmodule //top_module_sha256_top_64_256_s
